name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USERNAME: ${{ secrets.PGUSERNAME_TEST }}
          POSTGRES_PASSWORD: ${{ secrets.PGPASSWORD_TEST }}
          POSTGRES_DB: ${{ secrets.PGDATABASE_TEST }}
        ports:
          - 5432:5432

    strategy:
      matrix:
        node-version: [14.21.3]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.Js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install migrate and test
        run: |
          npm install
          npm run migrate up
          npm run test
        env:
          CI: true
          PGHOST_TEST: ${{ secrets.PGHOST_TEST }}
          PGPORT_TEST: ${{ secrets.PGPORT_TEST }}
          PGUSER_TEST: ${{ secrets.PGUSERNAME_TEST }}
          PGPASSWORD_TEST: ${{ secrets.PGPASSWORD_TEST }}
          PGDATABASE_TEST: ${{ secrets.PGDATABASE_TEST }}
          PGHOST: ${{ secrets.PGHOST_TEST }}
          PGPORT: ${{ secrets.PGPORT_TEST }}
          PGUSER: ${{ secrets.PGUSERNAME_TEST }}
          PGPASSWORD: ${{ secrets.PGPASSWORD_TEST }}
          PGDATABASE: ${{ secrets.PGDATABASE_TEST }}
          ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
          REFRESH_TOKEN_KEY: ${{ secrets.REFRESH_TOKEN_KEY }}
